# Nightly image doesn't support arm.
#FROM rustlang/rust:nightly
FROM rust:1.49

RUN rustup default nightly

WORKDIR /app

COPY . .

RUN apt-get update -qq
RUN cargo install diesel_cli --no-default-features --features postgres
ENTRYPOINT ["/bin/bash"]
