FROM rustlang/rust:nightly AS base

RUN cargo install cargo-watch

FROM base AS dev

WORKDIR /app

CMD cargo watch -c --poll -x check -s 'cargo run --bin main'
# `-poll` option is needed because of this issue: https://stackoverflow.com/questions/52996052/node-watch-on-a-docker-compose-volume-does-not-register-delete-events
