# Nightly image doesn't support arm.
#FROM rustlang/rust:nightly
FROM rust:1.49

RUN rustup default nightly

WORKDIR /app

RUN apt-get update -qq
RUN rm -rf /var/lib/apt/lists/*
RUN cargo install diesel_cli --no-default-features --features postgres
ENTRYPOINT ["/bin/bash"]
